"""add player guess-award rate limit fields

Revision ID: 6f062d668b36
Revises: f4b4838230fa
Create Date: 2026-08-23 17:04:25.516374

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f062d668b36"
down_revision: str | Sequence[str] | None = "f4b4838230fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column("guess_awards_today", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("players", sa.Column("guess_awards_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "guess_awards_date")
    op.drop_column("players", "guess_awards_today")
    # ### end Alembic commands ###
