"""add player currencies

Revision ID: cb0141d47427
Revises: 422efad039a9
Create Date: 2026-08-25 23:50:10.336993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb0141d47427"
down_revision: str | Sequence[str] | None = "422efad039a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_currencies",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "currency_type",
            sa.Enum("STANDARD_TICKET", "EVENT_TICKET", name="currencytype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.telegram_user_id"]),
        sa.PrimaryKeyConstraint("player_id", "currency_type"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_currencies")
    # ### end Alembic commands ###
