"""initial schema

Revision ID: f4b4838230fa
Revises:
Create Date: 2026-08-23 16:48:31.879544

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4b4838230fa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("anilist_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("series", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "rarity", sa.Enum("THREE_STAR", "FOUR_STAR", "FIVE_STAR", name="rarity"), nullable=False
        ),
        sa.Column("base_hp", sa.Integer(), nullable=False),
        sa.Column("base_atk", sa.Integer(), nullable=False),
        sa.Column("base_def", sa.Integer(), nullable=False),
        sa.Column("base_spd", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("anilist_id"),
    )
    op.create_table(
        "players",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("ley_shards", sa.Integer(), nullable=False),
        sa.Column("echoes", sa.Integer(), nullable=False),
        sa.Column("last_daily_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_trickle_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("telegram_user_id"),
    )
    op.create_table(
        "banners",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("STANDARD", "EVENT", name="bannertype"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_up_character_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["rate_up_character_id"],
            ["characters.anilist_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pity_state",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("banner_type", sa.Enum("STANDARD", "EVENT", name="bannertype"), nullable=False),
        sa.Column("pulls_since_last_5star", sa.Integer(), nullable=False),
        sa.Column("pulls_since_last_4star", sa.Integer(), nullable=False),
        sa.Column("guaranteed_rate_up", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.telegram_user_id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "banner_type"),
    )
    op.create_table(
        "player_characters",
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("copies_owned", sa.Integer(), nullable=False),
        sa.Column("first_obtained_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.anilist_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.telegram_user_id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "character_id"),
    )
    op.create_table(
        "pulls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("banner_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("pulled_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["banner_id"],
            ["banners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.anilist_id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.telegram_user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pulls")
    op.drop_table("player_characters")
    op.drop_table("pity_state")
    op.drop_table("banners")
    op.drop_table("players")
    op.drop_table("characters")
    # ### end Alembic commands ###
